<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit5e7bdb49466fb6196db6df6b182df8cd
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
        'P' => 
        array (
            'Psr\\Log\\' => 8,
        ),
        'O' => 
        array (
            'Ollyo\\Task\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
        'Psr\\Log\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/log/Psr/Log',
        ),
        'Ollyo\\Task\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PayPal' => 
            array (
                0 => __DIR__ . '/..' . '/paypal/rest-api-sdk-php/lib',
            ),
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit5e7bdb49466fb6196db6df6b182df8cd::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit5e7bdb49466fb6196db6df6b182df8cd::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit5e7bdb49466fb6196db6df6b182df8cd::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit5e7bdb49466fb6196db6df6b182df8cd::$classMap;

        }, null, ClassLoader::class);
    }
}
