<?php return array(
    'root' => array(
        'name' => 'ollyo/php-task',
        'pretty_version' => '1.0.0+no-version-set',
        'version' => '1.0.0.0',
        'reference' => null,
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        'ollyo/php-task' => array(
            'pretty_version' => '1.0.0+no-version-set',
            'version' => '1.0.0.0',
            'reference' => null,
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'paypal/rest-api-sdk-php' => array(
            'pretty_version' => '1.14.0',
            'version' => '1.14.0.0',
            'reference' => '72e2f2466975bf128a31e02b15110180f059fc04',
            'type' => 'library',
            'install_path' => __DIR__ . '/../paypal/rest-api-sdk-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'psr/log' => array(
            'pretty_version' => '1.1.4',
            'version' => '1.1.4.0',
            'reference' => 'd49695b909c3b7628b6289db5479a1c204601f11',
            'type' => 'library',
            'install_path' => __DIR__ . '/../psr/log',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'stripe/stripe-php' => array(
            'pretty_version' => 'v16.6.0',
            'version' => '16.6.0.0',
            'reference' => 'd6de0a536f00b5c5c74f36b8f4d0d93b035499ff',
            'type' => 'library',
            'install_path' => __DIR__ . '/../stripe/stripe-php',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
